version: '3'
services:
    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./django_server:/srv/docker-server
            - ./log:/var/log/nginx
        depends_on:
            - django

    django:
        container_name: django
        build: ./django_server
        image: docker-server/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
            - ./django_server:/srv/docker-server
            - ./log:/var/log/uwsgi
